export const sampleData = {
    nodes: [
        {
            name: 'INTERNET', nodeId: 'A-1', index: 1, color: '#2b95ec', child: {
                nodes: [
                    {
                        name: 'United States', nodeId: 'A-1', index: 1, color: '#2b95ec', child: {
                            nodes: [
                                {
                                    name: 'California', nodeId: 'A-1', index: 1, color: '#2b95ec', child: {
                                        nodes: [
                                            { name: '10.30.64.0/23', nodeId: 'A-1', color: '#2b95ec' },
                                            { name: 'Active-Directory', nodeId: 'X', color: '#000000' },
                                            { name: '10.30.64.0/23', nodeId: 'A-2', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'B-1', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'B-2', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'C-1', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'C-2', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'D-1', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'D-2', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'E-1', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'E-2', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'F-1', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'F-2', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'G-1', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'G-2', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'H-1', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'H-2', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'I-1', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'I-2', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'J-1', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'J-2', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'K-1', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'K-2', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'L-1', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'L-2', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'M-1', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'M-2', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'N-1', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'N-2', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'O-1', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'O-2', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'P-1', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'P-2', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'Q-1', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'Q-2', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'R-1', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'R-2', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'S-1', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'S-2', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'T-1', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'T-2', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'U-1', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'U-2', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'V-1', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'V-2', color: '#06d6a0' },
                                            { name: '10.30.64.0/23', nodeId: 'W-1', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'W-2', color: '#5300ff' },
                                            { name: '10.30.64.0/23', nodeId: 'X-1', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'X-2', color: '#ecaa17' },
                                            { name: '10.30.64.0/23', nodeId: 'Y-1', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'Y-2', color: '#780078' },
                                            { name: '10.30.64.0/23', nodeId: 'Z-1', color: '#2b95ec' },
                                            { name: '10.30.64.0/23', nodeId: 'Z-2', color: '#2b95ec' },
                                        ],
                                        links: [
                                            { source: 0, target: 1, value: 1, color: '#2b95ec' },
                                            { source: 1, target: 2, value: 2, color: '#2b95ec' },
                                            { source: 3, target: 1, value: 3, color: '#06d6a0' },
                                            { source: 1, target: 4, value: 1, color: '#06d6a0' },
                                            { source: 5, target: 1, value: 2, color: '#5300ff' },
                                            { source: 1, target: 6, value: 3, color: '#5300ff' },
                                            { source: 7, target: 1, value: 1, color: '#ecaa17' },
                                            { source: 1, target: 8, value: 2, color: '#ecaa17' },
                                            { source: 9, target: 1, value: 1, color: '#780078' },
                                            { source: 1, target: 10, value: 2, color: '#780078' },
                                            { source: 11, target: 1, value: 1, color: '#2b95ec' },
                                            { source: 1, target: 12, value: 2, color: '#2b95ec' },
                                            { source: 13, target: 1, value: 3, color: '#06d6a0' },
                                            { source: 1, target: 14, value: 1, color: '#06d6a0' },
                                            { source: 15, target: 1, value: 2, color: '#5300ff' },
                                            { source: 1, target: 16, value: 3, color: '#5300ff' },
                                            { source: 17, target: 1, value: 1, color: '#ecaa17' },
                                            { source: 1, target: 18, value: 2, color: '#ecaa17' },
                                            { source: 19, target: 1, value: 1, color: '#780078' },
                                            { source: 1, target: 20, value: 2, color: '#780078' },
                                            { source: 21, target: 1, value: 1, color: '#2b95ec' },
                                            { source: 1, target: 22, value: 2, color: '#2b95ec' },
                                            { source: 23, target: 1, value: 3, color: '#06d6a0' },
                                            { source: 1, target: 24, value: 1, color: '#06d6a0' },
                                            { source: 25, target: 1, value: 2, color: '#5300ff' },
                                            { source: 1, target: 26, value: 3, color: '#5300ff' },
                                            { source: 27, target: 1, value: 1, color: '#ecaa17' },
                                            { source: 1, target: 28, value: 2, color: '#ecaa17' },
                                            { source: 29, target: 1, value: 1, color: '#780078' },
                                            { source: 1, target: 30, value: 2, color: '#780078' },
                                            { source: 31, target: 1, value: 1, color: '#2b95ec' },
                                            { source: 1, target: 32, value: 2, color: '#2b95ec' },
                                            { source: 33, target: 1, value: 3, color: '#06d6a0' },
                                            { source: 1, target: 34, value: 1, color: '#06d6a0' },
                                            { source: 35, target: 1, value: 2, color: '#5300ff' },
                                            { source: 1, target: 36, value: 3, color: '#5300ff' },
                                            { source: 37, target: 1, value: 1, color: '#ecaa17' },
                                            { source: 1, target: 38, value: 2, color: '#ecaa17' },
                                            { source: 39, target: 1, value: 1, color: '#780078' },
                                            { source: 1, target: 40, value: 2, color: '#780078' },
                                            { source: 41, target: 1, value: 1, color: '#2b95ec' },
                                            { source: 1, target: 42, value: 2, color: '#2b95ec' },
                                            { source: 43, target: 1, value: 1, color: '#06d6a0' },
                                            { source: 1, target: 44, value: 2, color: '#06d6a0' },
                                            { source: 45, target: 1, value: 3, color: '#5300ff' },
                                            { source: 1, target: 46, value: 1, color: '#5300ff' },
                                            { source: 47, target: 1, value: 2, color: '#ecaa17' },
                                            { source: 1, target: 48, value: 3, color: '#ecaa17' },
                                            { source: 49, target: 1, value: 1, color: '#780078' },
                                            { source: 1, target: 50, value: 2, color: '#780078' },
                                            { source: 51, target: 1, value: 1, color: '#2b95ec' },
                                            { source: 1, target: 52, value: 2, color: '#2b95ec' }
                                        ]
                                    }
                                },
                                { name: 'Active-Directory', nodeId: 'X', color: '#000000' },
                                { name: 'California', nodeId: 'A-2', color: '#2b95ec' },
                                { name: 'Washington', nodeId: 'B-1', color: '#06d6a0' },
                                { name: 'Washington', nodeId: 'B-2', color: '#06d6a0' },
                                { name: 'New York', nodeId: 'C-1', color: '#5300ff' },
                                { name: 'New York', nodeId: 'C-2', color: '#5300ff' },
                                { name: 'Texas', nodeId: 'D-1', color: '#ecaa17' },
                                { name: 'Texas', nodeId: 'D-2', color: '#ecaa17' }
                            ],
                            links: [
                                { source: 0, target: 1, value: 1, color: '#2b95ec' },
                                { source: 1, target: 2, value: 2, color: '#2b95ec' },
                                { source: 3, target: 1, value: 3, color: '#06d6a0' },
                                { source: 1, target: 4, value: 1, color: '#06d6a0' },
                                { source: 5, target: 1, value: 2, color: '#5300ff' },
                                { source: 1, target: 6, value: 3, color: '#5300ff' },
                                { source: 7, target: 1, value: 1, color: '#ecaa17' },
                                { source: 1, target: 8, value: 2, color: '#ecaa17' }
                            ]
                        }
                    },
                    { name: 'Active-Directory', nodeId: 'X', color: '#000000' },
                    { name: 'United States', nodeId: 'A-2', color: '#2b95ec' },
                    { name: 'India', nodeId: 'B-1', color: '#06d6a0' },
                    { name: 'India', nodeId: 'B-2', color: '#06d6a0' },
                    { name: 'Australia', nodeId: 'C-1', color: '#5300ff' },
                    { name: 'Australia', nodeId: 'C-2', color: '#5300ff' },
                    { name: 'Canada', nodeId: 'D-1', color: '#ecaa17' },
                    { name: 'Canada', nodeId: 'D-2', color: '#ecaa17' },
                    { name: 'Iceland', nodeId: 'E-1', color: '#780078' },
                    { name: 'Iceland', nodeId: 'E-2', color: '#780078' },
                    { name: 'Brazil', nodeId: 'F-1', color: '#2b95ec' },
                    { name: 'Brazil', nodeId: 'F-2', color: '#2b95ec' },
                    { name: 'Mexico', nodeId: 'G-1', color: '#06d6a0' },
                    { name: 'Mexico', nodeId: 'G-2', color: '#06d6a0' }
                ],
                links: [
                    { source: 0, target: 1, value: 1, color: '#2b95ec' },
                    { source: 1, target: 2, value: 2, color: '#2b95ec' },
                    { source: 3, target: 1, value: 3, color: '#06d6a0' },
                    { source: 1, target: 4, value: 1, color: '#06d6a0' },
                    { source: 5, target: 1, value: 2, color: '#5300ff' },
                    { source: 1, target: 6, value: 3, color: '#5300ff' },
                    { source: 7, target: 1, value: 1, color: '#ecaa17' },
                    { source: 1, target: 8, value: 2, color: '#ecaa17' },
                    { source: 9, target: 1, value: 3, color: '#780078' },
                    { source: 1, target: 10, value: 1, color: '#780078' },
                    { source: 11, target: 1, value: 2, color: '#2b95ec' },
                    { source: 1, target: 12, value: 3, color: '#2b95ec' },
                    { source: 13, target: 1, value: 1, color: '#06d6a0' },
                    { source: 1, target: 14, value: 2, color: '#06d6a0' }
                ]
            }
        },
        { name: 'Active-Directory', nodeId: 'X', color: '#000000' },
        { name: 'INTERNET', nodeId: 'A-2', color: '#2b95ec' },
        { name: 'INTERNAL NETWORKS', nodeId: 'B-1', color: '#06d6a0' },
        { name: 'INTERNAL NETWORKS', nodeId: 'B-2', color: '#06d6a0' },
        { name: 'USER GROUPS', nodeId: 'C-1', color: '#5300ff' },
        { name: 'USER GROUPS', nodeId: 'C-2', color: '#5300ff' },
        { name: 'GROUP - TO - GROUP', nodeId: 'D-1', color: '#ecaa17' },
        { name: 'GROUP - TO - GROUP', nodeId: 'D-2', color: '#ecaa17' },
        { name: 'ROLE - TO - ROLE', nodeId: 'E-1', color: '#780078' },
        { name: 'ROLE - TO - ROLE', nodeId: 'E-2', color: '#780078' }
    ],
    links: [
        { source: 0, target: 1, value: 1, color: '#2b95ec' },
        { source: 1, target: 2, value: 2, color: '#2b95ec' },
        { source: 3, target: 1, value: 3, color: '#06d6a0' },
        { source: 1, target: 4, value: 1, color: '#06d6a0' },
        { source: 5, target: 1, value: 2, color: '#5300ff' },
        { source: 1, target: 6, value: 3, color: '#5300ff' },
        { source: 7, target: 1, value: 1, color: '#ecaa17' },
        { source: 1, target: 8, value: 2, color: '#ecaa17' },
        { source: 9, target: 1, value: 1, color: '#780078' },
        { source: 1, target: 10, value: 2, color: '#780078' }
    ]
};
